### ISSUE TITLE
feat: Ignore .git directories

### ISSUE THREAD

**Issue by dbalatero** [princejoogie/dir-telescope.nvim#10]
### What would you like?

By default, the directory picker initializes with a ton of directories in `.git` when the `hidden = true` option is set.

It would probably be good to either:
1. Have a configuration value to omit directory paths, `ignore_patterns = { ".git/*", "foo/bar/*" }`
2. Always hide version control directories like `.git` from users

Option 1 would be more flexible and I lean towards that one as a result!

### Additional notes

![image](https://user-images.githubusercontent.com/59429/227746682-91394afc-f618-47b2-9738-5210416876b7.png)

**Comment by princejoogie** [comment]
@dbalatero I cant seem to replicate this, may i know if you are using [fdfind](https://github.com/sharkdp/fd) or the default find command? (if running `which fd` in the terminal shows you a path)

**Comment by princejoogie** [comment]
@dbalatero this plugin still uses `telescope.nvim` so i believe you can add the `file_ignore_patterns` option in your telescope setup.

e.g.
```lua
require("telescope").setup({
  defaults = {
    file_ignore_patterns = {
      "node_modules/",
      ".git/",
      "dist/",
      "build/",
      "yarn.lock",
      "package-lock.json",
    },
  }
})
```

**Comment by kaka-ruto** [comment]
Can it auto ignore all the files/folders that are ignored by Telescope?

I have ripgrep installed so Telescope uses it (and auto ignores all that ripgrep ignores)

Would be nice if this extension also ignored whatever Telescope already ignores.
