### ISSUE TITLE
feat: timeout or way to abort initial search

### ISSUE THREAD

**Issue by matu3ba** [princejoogie/dir-telescope.nvim#2]
### What would you like?

If the initial search for files takes too long, then either a timeout should be used or a key for canceling the search be available.

### Additional notes

One may not know how long the initial search takes. For example, for me searching from $HOME makes neovim completely unresponsive without anyway to cancel the search.

**Comment by princejoogie** [comment]
@matu3ba i left some comments at #3, closing this as i will continue the conversation there. thanks for the feedback!
