### ISSUE TITLE
bug: hangs on large projects

### ISSUE THREAD

**Issue by dlvhdr** [princejoogie/dir-telescope.nvim#3]
### What happened?

Running this command takes a really long time as you're doing a `scan_dir` without any kind of lazy loading.

### Neovim Version

```shell
NVIM v0.9.0-dev-109-g0b71960ab-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by dolevh@IL-C02FG4W9MD6R

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-0b71960/share/nvim"

Run :checkhealth for more info
```

### Telescope.nvim Version

0.1.0

**Comment by princejoogie** [comment]
currently working on making this async and be able to cancel to not freeze neovim while performing scan_dir. related to #2.

**Comment by princejoogie** [comment]
@dlvhdr i did a few benchmarks with the new method in this PR: #4
mind if you could checkout to that branch and test it? thanks

| 782 files  | time (s) | blocking? |
| ---------- | -------: | --------- |
| new method | 0.032537 | false     |
| old method | 0.563939 | true      |

| 1268 files | time (s) | blocking? |
| ---------- | -------: | --------- |
| new method | 0.032654 | false     |
| old method | 0.591894 | true      |

| 373769 files | time (s) | blocking? |
| ------------ | -------: | --------- |
| new method   | 0.226896 | false     |
| old method   | 9.076255 | true      |

**Comment by princejoogie** [comment]
its currently in `dev` branch

```lua
use({
  "princejoogie/dir-telescope.nvim",
  requires = { "nvim-telescope/telescope.nvim" },
  branch = "dev",
  config = function()
    require("dir-telescope").setup({
      debug = true,
    })
  end,
})
```

`:GrepInDirectory` or `:FileInDirectory` for the new method
`:GrepInDirectorySlow` or `:FileInDirectorySlow` for the old method

`:messages` will contain the output of benchmark for each command

**Comment by dlvhdr** [comment]
Yeah checking it!

**Comment by dlvhdr** [comment]
Hmm it's still a quite slow but I noticed it searches my node_modules which is in my `.gitignore`

**Comment by princejoogie** [comment]
hmm, seems consistent in my tests. may i know what OS you're using? and for sanity sakes, double check you're on `dev` branch for the plugin and ran `:PackerSync`
