### ISSUE TITLE
bug: hidden=false and respect_gitignore=false are not respected within target dir of first selection

### ISSUE THREAD

**Issue by matu3ba** [princejoogie/dir-telescope.nvim#6]
### What happened?

After selection of the first selection, I can not select a gitignored directory to select a file.
I would expect, that either 1. .gitignore is not respected for both, 2. .gitignore is not respected for the target. 

The first selection should always be complete (up to a limit/timeout), as otherwise there is no way to select the vendored/generated/.gitignored subrepository.

### Neovim Version

```shell
NVIM v0.9.0-dev-280+gfae754073                                                                                                                                                                                     
Build type: RelWithDebInfo                                                                                                                                                                                         
LuaJIT 2.1.0-beta3
```

### Telescope.nvim Version

cc77713294892c5bbce26adee665114250624e6b

### Relevant log output

```shell
Please insert instruction for how to get the relevant log in here. Otherwise, it is not very useful.
```

### Additional notes

Relevant config:  

use { 'princejoogie/dir-telescope.nvim', config = function() require('dir-telescope').setup({hidden = false,respect_gitignore = false,}) end, }

map('n', '<leader>fd', [[<cmd>FileInDirectory<CR>]], opts) -- find files
map('n', '<leader>fs', [[<cmd>GrepInDirectory<CR>]], opts) -- forwardIntoDir searchstring

**Comment by princejoogie** [comment]
thanks for reporting @matu3ba, ill take a look at this

**Comment by princejoogie** [comment]
hey @matu3ba i think this happens because of the options you have set in you `telescope.nvim` plugin. explained here: (https://github.com/princejoogie/dir-telescope.nvim/issues/10#issuecomment-1483977524)
