### ISSUE TITLE
feat: accept previewer and theme options

### ISSUE THREAD

**Issue by aleprovencio** [princejoogie/dir-telescope.nvim#7]
### What would you like?

I don't feel that showing a previewer upon the directory selection is useful, can we have a way of configuring it?

**Comment by princejoogie** [comment]
definitely! the picker is just a normal telescope picker which you can pass your configurations to. will work on this, thanks

**Comment by jrnxf** [comment]
any update on this?

**Comment by jrnxf** [comment]
> definitely! the picker is just a normal telescope picker which you can pass your configurations to. will work on this, thanks

at the minute I don't think you give us any way to pass these in, though

**Comment by princejoogie** [comment]
this commit resolves this: https://github.com/princejoogie/dir-telescope.nvim/commit/1f3a041f870d1edf9cc64635e79f4b829e755978
